USE Restaurante

SELECT * FROM VENTA

/* INNER */
SELECT * FROM CLIENTE
INNER JOIN VENTA
ON CLIENTE.idCliente = VENTA.CLIENTE_idCliente

/* LEFT */
SELECT * FROM EMPLEADO
LEFT JOIN VENTA
ON EMPLEADO.idEmpleado = VENTA.CLIENTE_idCliente

/* RIGHT */
SELECT * FROM EMPLEADO
RIGHT JOIN VENTA
ON EMPLEADO.idEmpleado = VENTA.EMPLEADO_idEmpleado

/* OUTER */
SELECT EMPLEADO.nombre, EMPLEADO.apellido, CLIENTE.nombre, CLIENTE.apellido
FROM EMPLEADO
FULL OUTER JOIN CLIENTE
ON EMPLEADO.nombre = CLIENTE.nombre